# Use root/example as user/password credentials
version: '3.1'

services:  
  migration-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always  
    volumes:    
     - ./data_sql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: migration
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    ports:
      - "8806:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080